crypto:
  bucket:
    path: bucket
    read-chunk-size: 100
  summary:
    read-chunk-size: 1000

spring:
  application:
    name: crypto-importer
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: password
  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: "always"

