services:
  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD_FILE=/run/secrets/db_password
    secrets:
      - db_password
    ports:
      - "5432:5432"
    restart: always

secrets:
  db_password:
    file: db_password.txt
  